#!/bin/bash
# Template for install script - actual script is generated by server with token
set -e
echo "Miner Agent Install"
echo "Run: curl -sSL https://YOUR_SERVER/agents/install?token=YOUR_TOKEN | bash"
