#!/bin/bash
# Template for uninstall script - actual script is generated by server with token
set -e
echo "Miner Agent Uninstall"
echo "Run: curl -sSL https://YOUR_SERVER/agents/uninstall?token=YOUR_TOKEN | bash"
